### ISSUE TITLE
认领Fragment源码解析

### ISSUE THREAD

**Issue by huanglizhuo** [LittleFriendsGroup/AndroidSdkSourceAnalysis#14]

**Comment by CaMnter** [comment]
@huanglizhuo 好的(｡>﹏<｡)。

**Comment by nukc** [comment]
@huanglizhuo 源码解析相关请看：https://github.com/LittleFriendsGroup/AndroidSdkSourceAnalysis/issues/70

**Comment by huanglizhuo** [comment]
@nukc 实在抱歉 挖坑忘记填  最近可能没时间填坑  这次先放弃了
