### ISSUE TITLE
认领LayoutInflater/LayoutInflaterCompat源码分析

### ISSUE THREAD

**Issue by peerless2012** [LittleFriendsGroup/AndroidSdkSourceAnalysis#20]
以前为了研究LayoutInflater加载布局的三个参数,然后跟过,希望尽力做好!

**Comment by nukc** [comment]
好的，已经加上去了，加油！

**Comment by peerless2012** [comment]
[LayoutInflater/LayoutInflaterCompat源码分析](https://github.com/peerless2012/SourceAnalysis/blob/master/Android/FrameWork/LayoutInflater%26LayoutInflaterCompat%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90.md)
已经分析完毕，请核对，需要更正的地方可以[email](mailto:peerless2012@126.com)我，谢谢！

**Comment by nukc** [comment]
@peerless2012 好的

**Comment by nukc** [comment]
@android-cjj
