### ISSUE TITLE
认领 SharedPreferences/Preference

### ISSUE THREAD

**Issue by beautifulSoup** [LittleFriendsGroup/AndroidSdkSourceAnalysis#22]
如题

**Comment by nukc** [comment]
好的，已经加上去了。

**Comment by beautifulSoup** [comment]
SharedPreferences的源码分析  [Android SharedPreferences源码分析](http://sixwolf.net/blog/2016/05/03/Android_SharedPreferences%E6%BA%90%E7%A0%81%E5%88%86%E6%9E%90/)

**Comment by nukc** [comment]
@android-cjj

**Comment by android-cjj** [comment]
写到个人Github md中

**Comment by beautifulSoup** [comment]
那我给github上地址吧，应该不用放README吧       [https://github.com/beautifulSoup/beautifulSoup.github.io/blob/master/_posts/2016-05-03-Android_SharedPreferences%E6%BA%90%E7%A0%81%E5%88%86%E6%9E%90.md](https://github.com/beautifulSoup/beautifulSoup.github.io/blob/master/_posts/2016-05-03-Android_SharedPreferences%E6%BA%90%E7%A0%81%E5%88%86%E6%9E%90.md)

**Comment by beautifulSoup** [comment]
如果需要的话，我可以提pull request

**Comment by android-cjj** [comment]
格式不对 ，还要校对 ，加群聊吧

**Comment by beautifulSoup** [comment]
你好，477826523   这个群加不进去，下面那个群加了还没通过。 @android-cjj

**Comment by beautifulSoup** [comment]
修改了格式   [https://github.com/beautifulSoup/AndroidSourceAnalysis/blob/master/docs/2016-05-03-Android_SharedPreferences%E6%BA%90%E7%A0%81%E5%88%86%E6%9E%90.md](https://github.com/beautifulSoup/AndroidSourceAnalysis/blob/master/docs/2016-05-03-Android_SharedPreferences%E6%BA%90%E7%A0%81%E5%88%86%E6%9E%90.md)
