### ISSUE TITLE
认领LocalBroadcastManager源码解析

### ISSUE THREAD

**Issue by czhzero** [LittleFriendsGroup/AndroidSdkSourceAnalysis#43]

**Comment by nukc** [comment]
好的，已加。

**Comment by czhzero** [comment]
已经解析完成，请校验。https://github.com/czhzero/AndroidSdkSourceAnalysis/blob/master/article/LocalBroadcastManager%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90.md

**Comment by nukc** [comment]
@czhzero 请问你的这篇LocalBroadcastManager是根据api几解析的？

**Comment by czhzero** [comment]
23
