### ISSUE TITLE
认领Toolbar源码解析

### ISSUE THREAD

**Issue by mrchenmo** [LittleFriendsGroup/AndroidSdkSourceAnalysis#56]

**Comment by nukc** [comment]
:）Toolbar已经有人认领了，要不看看其他的

**Comment by shuicao192** [comment]
何谓有人认领，资源不是可以共享吗，认领了就没了？不理解

kigoss@126.com

发件人： C君
发送时间： 2016-07-07 14:08
收件人： LittleFriendsGroup/AndroidSdkSourceAnalysis
主题： Re: [LittleFriendsGroup/AndroidSdkSourceAnalysis] 认领Toolbar源码解析 (#56)
:）Toolbar已经有人认领了，要不看看其他的

**Comment by nukc** [comment]
@shuicao192 是这样的，Toolbar已经由@SeniorZhai 认领了，到时候会公布他审核通过后的文章以让大家一起学习，不让二次认领是不想再占用大家的宝贵时间去分析同一个源码。现在还有很多待认领的源码解析，你可以看看，大家都可以踊跃参与。:)

**Comment by shuicao192** [comment]
OK，那你方便发下没被认领的源码分析，我选择我所接触过的，结合自己经验看尝试处理下。抱歉昨天言辞唐突，主要第一次参与这样的活动，还请见谅。

kigoss@126.com

发件人： C君
发送时间： 2016-07-09 14:29
收件人： LittleFriendsGroup/AndroidSdkSourceAnalysis
抄送： caomian; Mention
主题： Re: [LittleFriendsGroup/AndroidSdkSourceAnalysis] 认领Toolbar源码解析 (#56)
@shuicao192 是这样的，Toolbar已经由@SeniorZhai 认领了，到时候会公布他审核通过后的文章以让大家一起学习，不让二次认领是不想再占用大家的宝贵时间去分析同一个源码。现在还有很多待认领的源码解析，你可以看看，大家都可以踊跃参与。:)

**Comment by nukc** [comment]
@shuicao192 README.md里有写，可以查看一下。

**Comment by shuicao192** [comment]
ok，我看看，给你答复

kigoss@126.com

发件人： C君
发送时间： 2016-07-13 15:02
收件人： LittleFriendsGroup/AndroidSdkSourceAnalysis
抄送： caomian; Mention
主题： Re: [LittleFriendsGroup/AndroidSdkSourceAnalysis] 认领Toolbar源码解析 (#56)
@shuicao192 README.md里有写，可以查看一下。
