### ISSUE TITLE
SparseArray分析

### ISSUE THREAD

**Issue by THEONE10211024** [LittleFriendsGroup/AndroidSdkSourceAnalysis#9]
如题

**Comment by nukc** [comment]
我看了下，SparseArrayCompat已经有人分析了。 ：)

**Comment by THEONE10211024** [comment]
二者还是有区别的，要不分析一下？正好做个对比~

**Comment by nukc** [comment]
比较区别的话，同一个人一起分析会不会好点？也能快点，这样也能节约你的时间，很欢迎你认领其他。

**Comment by peerless2012** [comment]
怎么联系认领?想参与进来,而不是当一个看客

**Comment by nukc** [comment]
@peerless2012 你可以直接在这里说你想分析什么，也可以new issue。

**Comment by THEONE10211024** [comment]
可以分析Volley不？

**Comment by nukc** [comment]
@THEONE10211024 可以的，你确定的话就加上去了，或者你自己也可以加啊。。。。。

**Comment by nukc** [comment]
@THEONE10211024 我等你的回复

**Comment by THEONE10211024** [comment]
行，那我就来分析volley吧

**Comment by FreeSunny** [comment]
我之前做过Sparse*Array容器解析 http://blog.csdn.net/xueshanhaizi/article/details/51045750
